#!/usr/bin/env bash
# DUM-E's roles as live Buzz agents.
#
# One container per role, and that is the point: buzz-acp's own README says all
# workers under a single `--agents N` instance share one Nostr identity, so a
# pool cannot stand in for epistemically independent roles. Each role here gets
# its own process, its own key, and only the channels it is seated in.
#
# The runtime per role is not chosen here — it is read from bindings.json, which
# is generated by DUM-E's own RuntimeRegistry.bind(). Buzz executes; DUM-E
# decides (BZ-042).
set -euo pipefail
cd "$(dirname "$0")"

RELAY="wss://otonom-cluster-0.taile59b41.ts.net"
# The human, as the Desktop signs. The owner is always implicitly allowed.
OWNER_PUBKEY="9d07f4c96b5e9e890c950769d73eac26b3186581ab7862295dad92e90734e09c"
# DUM-E's own voices, so the harness can drive a role without a human typing.
ALLOWLIST="$(python3 -c "
import json,pathlib
d=json.loads(pathlib.Path('../../secrets/roles.json').read_text())
o=json.loads(pathlib.Path('../../secrets/owner.json').read_text())
print(','.join([o['pubkey'], d['dume_orchestrator']['pubkey']]))")"
SECRETS="$PWD/../../secrets"
APP="$PWD/../desktop/squashfs-root"
IMAGE=dume-agent:0.5.18

# Endpoints for the local families, by runtime id.
declare -A ENDPOINT=(
  [qwen-local]="http://127.0.0.1:8000/v1"
  [mistral-local]="http://127.0.0.1:8001/v1"
)

roles() { python3 -c "import json;print(' '.join(json.load(open('bindings.json'))['roles']))"; }
field() { python3 -c "import json,sys;print(json.load(open('bindings.json'))['roles'][sys.argv[1]][sys.argv[2]])" "$1" "$2"; }
channels() { python3 -c "import json,sys;print(','.join(json.load(open('bindings.json'))['roles'][sys.argv[1]]['channels'].values()))" "$1"; }
key() { python3 -c "import json,sys;print(json.load(open(sys.argv[1]))['role:'+sys.argv[2]]['private'])" "$SECRETS/roles.json" "$1"; }

case "${1:-start}" in
  stop)   for r in $(roles); do docker rm -f "dume-agent-$r" >/dev/null 2>&1 || true; done; echo "stopped"; exit 0 ;;
  status) docker ps -a --filter "name=dume-agent-" --format '{{.Names}}\t{{.Status}}'; exit 0 ;;
  logs)   exec docker logs -f "dume-agent-${2:?usage: ./run-agents.sh logs <role>}" ;;
esac

for role in $(roles); do
  runtime=$(field "$role" runtime_id)
  endpoint="${ENDPOINT[$runtime]:-}"

  if [ -z "$endpoint" ]; then
    # claude-* and codex-* reach their provider through a CLI signed in with a
    # subscription. The ACP adapters (codex-acp, claude-agent-acp) require an
    # API key instead, which this host does not hold, so these roles stay on
    # DUM-E's own executor. The pack allows exactly this: "a mixed per-role
    # outcome is valid."
    echo "  $role → $runtime : DUM-E executor (no ACP adapter without an API key)"
    continue
  fi

  mkdir -p "$PWD/work/$role"
  docker rm -f "dume-agent-$role" >/dev/null 2>&1 || true
  docker run -d --name "dume-agent-$role" \
    --network host \
    -e BUZZ_AGENT_PROVIDER=openai \
    -e OPENAI_COMPAT_BASE_URL="$endpoint" \
    -e OPENAI_COMPAT_API_KEY=local-no-auth \
    -e OPENAI_COMPAT_MODEL="$(python3 -c "
import json,urllib.request,sys
u=sys.argv[1]+'/models'
print(json.load(urllib.request.urlopen(u,timeout=5))['data'][0]['id'])" "$endpoint")" \
    -e PATH=/opt/buzz/usr/bin:/usr/local/bin:/usr/bin:/bin \
    -v "$APP:/opt/buzz:ro" \
    -v "$PWD/prompts:/prompts:ro" \
    -v "$PWD/work/$role:/home/ubuntu/.buzz" \
    "$IMAGE" \
      --relay-url "$RELAY" \
      --private-key "$(key "$role")" \
      --agent-owner "$OWNER_PUBKEY" \
      --respond-to allowlist \
      --respond-to-allowlist "$ALLOWLIST" \
      --agent-command buzz-agent \
      --agent-args "" \
      `# Without an MCP command the agent has no tool to speak with: it generates
       # a reply and nothing publishes it. The harness wires the Buzz CLI through
       # this. Each role gets its own workspace so one cannot read another's.` \
      --mcp-command buzz-dev-mcp \
      --channels "$(channels "$role")" \
      --system-prompt-file "/prompts/$role.md" \
      --dedup queue \
    >/dev/null
  echo "  $role → $runtime : started"
done

echo
echo "status: ./run-agents.sh status   logs: ./run-agents.sh logs <role>"
