#!/usr/bin/env bash
# DUM-E's roles as live Buzz agents.
#
# One container per role, and that is the point: buzz-acp's own README says all
# workers under a single `--agents N` instance share one Nostr identity, so a
# pool cannot stand in for epistemically independent roles. Each role here gets
# its own process, its own key, and only the channels it is seated in.
#
# The runtime per role is not chosen here — it is read from bindings.json, which
# is generated by DUM-E's own RuntimeRegistry.bind(). Buzz executes; DUM-E
# decides (BZ-042).
set -euo pipefail
cd "$(dirname "$0")"
# The deployment address, from one place. See deploy/host.env.example.
DUME_BUZZ_HOST_WSS=""; DUME_BUZZ_HOST_HTTPS=""
. "../../deploy/host.env"
DUME_BUZZ_HOST_WSS="wss://$DUME_BUZZ_HOST"
DUME_BUZZ_HOST_HTTPS="https://$DUME_BUZZ_HOST"

RELAY="${DUME_BUZZ_HOST_WSS}"
# The human, as the Desktop signs. The owner is always implicitly allowed.
OWNER_PUBKEY="9d07f4c96b5e9e890c950769d73eac26b3186581ab7862295dad92e90734e09c"
# DUM-E's own voices, so the harness can drive a role without a human typing.
ALLOWLIST="$(python3 -c "
import json,pathlib
d=json.loads(pathlib.Path('../../secrets/roles.json').read_text())
o=json.loads(pathlib.Path('../../secrets/owner.json').read_text())
print(','.join([o['pubkey'], d['dume_orchestrator']['pubkey']]))")"
SECRETS="$PWD/../../secrets"
APP="$PWD/../desktop/squashfs-root"
IMAGE=dume-agent:0.5.18
CLAUDE_ROLES="commissioning_orchestrator spec_reviewer code_reviewer"
# codex-acp 1.6.2 offers a chat-gpt auth method and opens a session on the
# CLI's subscription — the note that it demands an OPENAI_API_KEY was true
# of an older build. Keeping the verifier on gpt also keeps three families
# in the channel rather than one.
CODEX_ROLES="verifier"
# BZ-036. A reviewer that carries yesterday's conversation into today's review
# is reading its own earlier reasoning as if it were evidence, and a verifier
# that does it is not a fresh verification at all. One turn per session drops
# the context between mentions, so each judgement starts from the packet and the
# artefact rather than from what it decided last time.
#
# The pack is explicit that !rotate is a useful mechanism and not by itself
# proof of freshness — proof is that there is no prior turn to carry.
FRESH_SESSION_ROLES="spec_reviewer code_reviewer verifier"

# Endpoints for the local families, by runtime id.
declare -A ENDPOINT=(
  [qwen-local]="http://127.0.0.1:8000/v1"
  [mistral-local]="http://127.0.0.1:8001/v1"
)

roles() { python3 -c "import json;print(' '.join(json.load(open('bindings.json'))['roles']))"; }
field() { python3 -c "import json,sys;print(json.load(open('bindings.json'))['roles'][sys.argv[1]][sys.argv[2]])" "$1" "$2"; }
channels() { python3 -c "import json,sys;print(','.join(json.load(open('bindings.json'))['roles'][sys.argv[1]]['channels'].values()))" "$1"; }
key() { python3 -c "
import json,sys
d=json.load(open(sys.argv[1])); r=sys.argv[2]
# The front desk speaks as DUM-E itself, so it uses the application identity —
# the one carrying the name and the mark — not the orchestrator role slot.
print((d['dume_orchestrator'] if r=='commissioning_orchestrator' else d['role:'+r])['private'])" "$SECRETS/roles.json" "$1"; }

case "${1:-start}" in
  stop)   for r in $(roles); do docker rm -f "dume-agent-$r" >/dev/null 2>&1 || true; done; echo "stopped"; exit 0 ;;
  status) docker ps -a --filter "name=dume-agent-" --format '{{.Names}}\t{{.Status}}'; exit 0 ;;
  logs)   exec docker logs -f "dume-agent-${2:?usage: ./run-agents.sh logs <role>}" ;;
esac

for role in $(roles); do
  runtime=$(field "$role" runtime_id)
  endpoint="${ENDPOINT[$runtime]:-}"

  # Only two families can speak in a channel. Qwen calls the tool that posts;
  # Mistral answers in seven tokens and never sends, so it is silent here. Codex
  # cannot run at all — codex-acp wants an OPENAI_API_KEY and this host holds a
  # ChatGPT subscription. claude-agent-acp needs no key, so the reviewer roles
  # speak through it.
  case " $CLAUDE_ROLES " in *" $role "*) USE_CLAUDE=1 ;; *) USE_CLAUDE=0 ;; esac
  case " $CODEX_ROLES " in *" $role "*) USE_CODEX=1 ;; *) USE_CODEX=0 ;; esac
  case " $FRESH_SESSION_ROLES " in
    *" $role "*) FRESH="--max-turns-per-session 1" ;;
    *) FRESH="" ;;
  esac
  if [ "$USE_CODEX" = "1" ]; then
    docker rm -f "dume-agent-$role" >/dev/null 2>&1 || true
    mkdir -p "$PWD/work/$role"
    docker run -d --name "dume-agent-$role" \
      --network host \
      -e PATH=/opt/node/bin:/opt/buzz/usr/bin:/opt/codex/bin:/usr/local/bin:/usr/bin:/bin \
      -e HOME=/home/ubuntu \
      -e BUZZ_PRIVATE_KEY="$(key "$role")" \
      -e BUZZ_RELAY_URL="$RELAY" \
      -v "$HOME/.hermes/node:/opt/node:ro" \
      -v "$APP:/opt/buzz:ro" \
      -v "$PWD/prompts:/prompts:ro" \
      -v "$PWD/acp:/opt/acp:ro" \
      -v "$HOME/.codex:/home/ubuntu/.codex" \
      -v "$PWD/work/$role:/home/ubuntu/.buzz" \
      "$IMAGE" \
        --relay-url "$RELAY" \
        --private-key "$(key "$role")" \
        --agent-owner "$OWNER_PUBKEY" \
        --respond-to allowlist \
        --respond-to-allowlist "$ALLOWLIST" \
        --agent-command /opt/acp/node_modules/.bin/codex-acp \
        --agent-args "" \
        --channels "$(channels "$role")" \
        --system-prompt-file "/prompts/$role.md" \
        --dedup queue \
        ${FRESH} \
      >/dev/null
    echo "  $role → codex / gpt-5.6 (ChatGPT subscription) : started"
    continue
  fi
  if [ "$USE_CLAUDE" = "1" ]; then
    docker rm -f "dume-agent-$role" >/dev/null 2>&1 || true
    mkdir -p "$PWD/work/$role"
    docker run -d --name "dume-agent-$role" \
      --network host \
      `# ubuntu:24.04 ships Node 18 and the adapter needs newer, so the host
       # install is mounted and put first on PATH. It wants GLIBC_2.28; the
       # image provides 2.39.` \
      -e PATH=/opt/node/bin:/opt/buzz/usr/bin:/opt/claude/bin:/usr/local/bin:/usr/bin:/bin \
      -e HOME=/home/ubuntu \
      `# The agent posts its reply by running the Buzz CLI, which signs with its
       # own identity. buzz-agent inherits these from the harness; this adapter
       # is a separate process tree and does not, so its first send failed with
       # auth_error and the answer sat unposted.` \
      -e BUZZ_PRIVATE_KEY="$(key "$role")" \
      -e BUZZ_RELAY_URL="$RELAY" \
      -v "$HOME/.hermes/node:/opt/node:ro" \
      -v "$APP:/opt/buzz:ro" \
      -v "$PWD/prompts:/prompts:ro" \
      -v "$PWD/acp:/opt/acp:ro" \
      -v "$HOME/.local/share/claude:/opt/claude/share:ro" \
      -v "$HOME/.local/bin/claude:/opt/claude/bin/claude:ro" \
      -v "$HOME/.claude:/home/ubuntu/.claude" \
      -v "$PWD/work/$role:/home/ubuntu/.buzz" \
      "$IMAGE" \
        --relay-url "$RELAY" \
        --private-key "$(key "$role")" \
        --agent-owner "$OWNER_PUBKEY" \
        --respond-to allowlist \
        --respond-to-allowlist "$ALLOWLIST" \
        --agent-command /opt/acp/node_modules/.bin/claude-agent-acp \
        --agent-args "" \
        --channels "$(channels "$role")" \
        --system-prompt-file "/prompts/$role.md" \
        --dedup queue \
        ${FRESH} \
      >/dev/null
    echo "  $role → claude (CLI subscription, no API key) : started"
    continue
  fi

  if [ -z "$endpoint" ]; then
    # codex-acp wants an OPENAI_API_KEY and this host holds a ChatGPT
    # subscription, so codex roles stay on DUM-E's own executor. claude-agent-acp
    # turned out to need no key at all — it reports apiType=native and reuses the
    # CLI's session — so the front desk runs on it above. The pack allows the
    # split: "a mixed per-role outcome is valid."
    echo "  $role → $runtime : DUM-E executor (no ACP adapter without an API key)"
    continue
  fi

  # Every agent gets buzz-dev-mcp, including the one that only talks. The shell
  # is not an extra there: buzz-acp does not publish the reply itself — the
  # agent posts it by running the Buzz CLI, so the shell *is* the voice. Taking
  # it away produced an agent that thought for 50 seconds and said nothing.
  # deploy/dume-agents/mcp/desk-mcp.py keeps the narrower attempt for the day a
  # send-message tool can replace the shell.
  MCP_ARGS="--mcp-command buzz-dev-mcp"
  mkdir -p "$PWD/work/$role"
  docker rm -f "dume-agent-$role" >/dev/null 2>&1 || true
  docker run -d --name "dume-agent-$role" \
    --network host \
    -e BUZZ_AGENT_PROVIDER=openai \
    -e OPENAI_COMPAT_BASE_URL="$endpoint" \
    -e OPENAI_COMPAT_API_KEY=local-no-auth \
    -e OPENAI_COMPAT_MODEL="$(python3 -c "
import json,urllib.request,sys
u=sys.argv[1]+'/models'
print(json.load(urllib.request.urlopen(u,timeout=5))['data'][0]['id'])" "$endpoint")" \
    -e PATH=/opt/buzz/usr/bin:/usr/local/bin:/usr/bin:/bin \
    -v "$APP:/opt/buzz:ro" \
    -v "$PWD/prompts:/prompts:ro" \
    -v "$PWD/mcp:/opt/mcp:ro" \
    -v "$PWD/work/$role:/home/ubuntu/.buzz" \
    "$IMAGE" \
      --relay-url "$RELAY" \
      --private-key "$(key "$role")" \
      --agent-owner "$OWNER_PUBKEY" \
      --respond-to allowlist \
      --respond-to-allowlist "$ALLOWLIST" \
      --agent-command buzz-agent \
      --agent-args "" \
      `# Without an MCP command the agent has no tool to speak with: it generates
       # a reply and nothing publishes it. The harness wires the Buzz CLI through
       # this. Each role gets its own workspace so one cannot read another's.` \
      ${MCP_ARGS} \
      --channels "$(channels "$role")" \
      --system-prompt-file "/prompts/$role.md" \
      --dedup queue \
    >/dev/null
  echo "  $role → $runtime : started"
done

echo
echo "status: ./run-agents.sh status   logs: ./run-agents.sh logs <role>"
